version: '3'

services:
  chat2api:
    image: niansuh/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    volumes:
      - ./data:/app/data # Mount some data that needs to be saved
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - ARK0SE_TOKEN_URL=http://ark0se:5006/token # Already built-in, do not change

  ark0se:
    image: lanqian528/funcaptcha_solver:latest
    container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
    environment:
      - TZ=Asia/Shanghai # Set the time zone
